title: "Du Bon Sens"
description: "Il est temps que le citoyen belge reprenne les rênes de son destin. 'Du Bon Sens' propose une rupture avec le système actuel : fini les blocages et les compromissions qui trahissent votre vote. Notre objectif ? Une véritable démocratie directe, inspirée du modèle suisse mais propulsée par la technologie (Blockchain) pour garantir des votations sécurisées. Ici, les politiciens proposent, les citoyens disposent. Ce podcast est avant tout une invitation à la réflexion collective. Rendez-vous sur dubonsens.be pour poser vos questions ou recevoir le 'Manifeste pour une Démocratie 2.0'."
url: "https://www.dubonsens.be"
author: "Vincent Musschoot"
email: "contact@dubonsens.be"

# Configuration des collections (Podcasts et Blog)
collections:
  podcasts:
    output: true
    permalink: /podcasts/:slug/
  blog:
    output: true
    permalink: /blog/:slug/

# Règle pour appliquer le design automatiquement
defaults:
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "podcast"
