title: "Du Bon Sens"
description: "Il est temps que le citoyen belge reprenne les rênes de son destin. Le Mouvement Citoyen Belge de Démocratie Participative propose une rupture avec le système actuel : fini les blocages et les compromissions qui trahissent votre vote. Notre objectif ? Une véritable démocratie directe et souveraine, inspirée du modèle suisse mais propulsée par la technologie (Blockchain). Ici, les politiciens proposent, les citoyens disposent. Rendez-vous sur dubonsens.be pour recevoir notre 'Manifeste du Bon Sens'."
url: "https://www.dubonsens.be"
author: "Vincent Musschoot"
email: "contact@dubonsens.be"

# Configuration des collections (Podcasts et Blog)
collections:
  podcasts:
    output: true
    permalink: /podcasts/:slug/
  blog:
    output: true
    permalink: /blog/:slug/

# Règle pour appliquer le design automatiquement
defaults:
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "podcast"
