title: "Du Bon Sens"
description: "Il est temps que le citoyen belge reprenne les rênes de son destin. Place à la démocratie directe et à la blockchain : les politiciens proposent, vous décidez. Ce podcast est une invitation à la réflexion. Rendez-vous sur dubonsens.be pour poser vos questions ou recevoir le 'Manifeste pour une Démocratie 2.0'."
url: "https://www.dubonsens.be"
author: "Vincent Musschoot"
email: "contact@dubonsens.be"

# Configuration des collections (Podcasts et Blog)
collections:
  podcasts:
    output: true
    permalink: /podcasts/:slug/
  blog:
    output: true
    permalink: /blog/:slug/

# Règle pour appliquer le design automatiquement
defaults:
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "podcast"
