title: "Du Bon Sens"
url: "https://dubonsens.netlify.app" # Nous changerons Ã§a plus tard pour votre .com

# Configuration des collections (Podcasts et Blog)
collections:
  podcasts:
    output: true
    permalink: /podcasts/:slug/
  blog:
    output: true
    permalink: /blog/:slug/
