title: "Du Bon Sens"
url: "https://www.dubonsens.be"

# Configuration des collections (Podcasts et Blog)
collections:
  podcasts:
    output: true
    permalink: /podcasts/:slug/
  blog:
    output: true
    permalink: /blog/:slug/

# RÃ¨gle pour appliquer le design automatiquement
defaults:
  - scope:
      path: ""
      type: "podcasts"
    values:
      layout: "podcast"
